name: Test Workflow

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Print message
              run: echo "Testing workflow run"
